name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
        
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: alibayramcavus/gpacalculatorforheroku:latest
        
    - name: Push to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: gpacalculatorforheroku
        heroku_email: alibayramcavus@hotmail.com
